### ISSUE TITLE
Is it possible to choose the directory of local repository

### ISSUE THREAD

**Issue by lief-y** [OrangeX4/vscode-typst-sync#1]
The extension works well. However, is it possible to choose a different directory to store all local packages? Thank you!

**Comment by OrangeX4** [comment]
I'm afraid not, because the directory of local packages is set by typst, and this extension can't change it.

**Comment by lief-y** [comment]
> I'm afraid not, because the directory of local packages is set by typst, and this extension can't change it.

Thank you so much for your prompt reply and your explanation. I will ask the typst group to see if this can be done in the future.
